package mocks

import "github.com/arielizuardi/ezra/feedback/usecase"
import "github.com/stretchr/testify/mock"

// FeedbackUsecase is an autogenerated mock type for the FeedbackUsecase type
type FeedbackUsecase struct {
	mock.Mock
}

// StorePresenterFeedbackWithMapping provides a mock function with given fields: presenterID, classID, mappings, values
func (_m *FeedbackUsecase) StorePresenterFeedbackWithMapping(presenterID int64, classID int64, mappings []*usecase.Mapping, values [][]string) error {
	ret := _m.Called(presenterID, classID, mappings, values)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, []*usecase.Mapping, [][]string) error); ok {
		r0 = rf(presenterID, classID, mappings, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
