package mocks

import "github.com/stretchr/testify/mock"

import "github.com/arielizuardi/ezra/presenter"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FetchAllPresenters provides a mock function with given fields:
func (_m *Repository) FetchAllPresenters() ([]*presenter.Presenter, error) {
	ret := _m.Called()

	var r0 []*presenter.Presenter
	if rf, ok := ret.Get(0).(func() []*presenter.Presenter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*presenter.Presenter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPresenter provides a mock function with given fields: presenterID
func (_m *Repository) GetPresenter(presenterID int64) (*presenter.Presenter, error) {
	ret := _m.Called(presenterID)

	var r0 *presenter.Presenter
	if rf, ok := ret.Get(0).(func(int64) *presenter.Presenter); ok {
		r0 = rf(presenterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*presenter.Presenter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(presenterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorePresenter provides a mock function with given fields: p
func (_m *Repository) StorePresenter(p *presenter.Presenter) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*presenter.Presenter) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
