package mocks

import "github.com/stretchr/testify/mock"

import "github.com/arielizuardi/ezra/presenter"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Get provides a mock function with given fields: presenterID
func (_m *Repository) Get(presenterID int64) (*presenter.Presenter, error) {
	ret := _m.Called(presenterID)

	var r0 *presenter.Presenter
	if rf, ok := ret.Get(0).(func(int64) *presenter.Presenter); ok {
		r0 = rf(presenterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*presenter.Presenter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(presenterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
